-- Migration: Add task_name and minio_base_path to agent_tasks
-- Created: 2025-12-11
-- Purpose: Support hierarchical MinIO storage and human-readable task names

-- Add new columns
ALTER TABLE agent_tasks
ADD COLUMN IF NOT EXISTS task_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS minio_base_path TEXT;

-- Add index for task_name (for listing similar tasks)
CREATE INDEX IF NOT EXISTS idx_agent_tasks_task_name ON agent_tasks(task_name);

-- Add comments explaining structure
COMMENT ON COLUMN agent_tasks.task_name IS 'Human-readable task name generated by LLM (e.g., sales_analysis_chart)';
COMMENT ON COLUMN agent_tasks.minio_base_path IS 'Base MinIO path for this task execution (e.g., projects/{project_id}/{user}/agent-tasks/{task_name}/{task_id}/)';

-- Backfill existing tasks with default task names
UPDATE agent_tasks
SET task_name = 'legacy_task_' || substring(task_id from 6)
WHERE task_name IS NULL;

-- Migration verification
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'agent_tasks'
        AND column_name = 'task_name'
    ) THEN
        RAISE NOTICE '✅ Migration 014 completed: task_name and minio_base_path columns added';
    ELSE
        RAISE EXCEPTION '❌ Migration 014 failed: columns not created';
    END IF;
END $$;
