#!/usr/bin/env python3
"""
Diagnostic script to compare Template Extractor vs Smart Extractor
Tests both methods on the same URL to identify differences
"""

import asyncio
import sys
import os
import logging
from pathlib import Path

# Add backend to path
backend_path = Path(__file__).parent.parent.parent / "backend"
sys.path.insert(0, str(backend_path))

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

async def test_template_extraction():
    """Test Template Extractor with screener.in"""
    from app.services.template_extraction_service import (
        template_extraction_service,
        get_screener_in_template
    )

    logger.info("="*80)
    logger.info("TESTING TEMPLATE EXTRACTOR")
    logger.info("="*80)

    url = "https://www.screener.in/company/BHARTIARTL/consolidated/"
    template = get_screener_in_template()

    logger.info(f"URL: {url}")
    logger.info(f"Template: {template.name}")
    logger.info(f"Number of fields: {len(template.fields)}")
    logger.info("\nTemplate Fields:")
    for field in template.fields:
        logger.info(f"  - {field.name}: selector={field.selector}, type={field.data_type}")

    # Initialize and extract
    await template_extraction_service.initialize()

    try:
        result = await template_extraction_service.extract_data(
            url=url,
            template=template
        )

        logger.info("\n" + "="*80)
        logger.info("TEMPLATE EXTRACTION RESULTS")
        logger.info("="*80)
        logger.info(f"Success: {result['success']}")

        if result['success']:
            logger.info(f"Rows extracted: {result['row_count']}")
            logger.info("\nExtracted Data:")
            for row in result['data']:
                for key, value in row.items():
                    logger.info(f"  {key}: {value}")
        else:
            logger.error(f"Error: {result.get('error', 'Unknown error')}")

        return result

    finally:
        await template_extraction_service.close()


async def test_smart_extraction():
    """Test Smart Extractor with the same URL"""
    from app.services.webscraper.templates.template_auto_generator import TemplateAutoGenerator
    from app.services.llm_service import llm_service
    from app.services.scraper_service import scraper_service

    logger.info("\n" + "="*80)
    logger.info("TESTING SMART EXTRACTOR")
    logger.info("="*80)

    url = "https://www.screener.in/company/BHARTIARTL/consolidated/"
    user_instructions = "Extract company financial data including market cap, current price, P/E ratio, book value, dividend yield, ROCE, ROE, and face value"

    logger.info(f"URL: {url}")
    logger.info(f"User Instructions: {user_instructions}")
    logger.info(f"LLM Provider: ollama")

    # Initialize auto-generator
    auto_gen = TemplateAutoGenerator(
        llm_service=llm_service,
        scraper_service=scraper_service
    )

    # Generate template
    logger.info("\n--- Generating template from user instructions ---")
    template = await auto_gen.generate_template_from_user_instructions(
        url=url,
        user_instructions=user_instructions,
        llm_provider="ollama",
        include_smart_mapping=True
    )

    if not template:
        logger.error("Failed to generate template!")
        return None

    logger.info("\n" + "="*80)
    logger.info("SMART EXTRACTOR - GENERATED TEMPLATE")
    logger.info("="*80)
    logger.info(f"Template Name: {template.name}")
    logger.info(f"Description: {template.description}")
    logger.info(f"Number of fields: {len(template.fields)}")
    logger.info(f"Template Type: {template.schema_definition.type}")
    logger.info(f"Generated By: {template.schema_definition.metadata.get('generated_by')}")
    logger.info(f"Is Fallback: {template.schema_definition.metadata.get('fallback', False)}")
    logger.info(f"Confidence: {template.schema_definition.metadata.get('confidence')}")

    logger.info("\nGenerated Fields:")
    for field in template.fields:
        logger.info(f"\n  Field: {field.name}")
        logger.info(f"    Display Name: {field.display_name}")
        logger.info(f"    Type: {field.type}")
        logger.info(f"    Required: {field.required}")
        if field.source_hint:
            logger.info(f"    Source Type: {field.source_hint.type}")
            logger.info(f"    Extraction Hint: {field.source_hint.selector or field.source_hint.xpath or field.source_hint.pattern or field.source_hint.prompt}")

    return template


async def test_webpage_content():
    """Test what content is actually being fetched from the URL"""
    from app.services.scraper_service import scraper_service

    logger.info("\n" + "="*80)
    logger.info("TESTING WEBPAGE CONTENT FETCH")
    logger.info("="*80)

    url = "https://www.screener.in/company/BHARTIARTL/consolidated/"

    logger.info(f"Fetching content from: {url}")

    # Fetch without saving to DB
    result = await scraper_service.scrape_url(url, db=None)

    logger.info(f"\nContent fetched:")
    logger.info(f"  HTML length: {len(result.get('html', ''))} bytes")
    logger.info(f"  Text length: {len(result.get('text', ''))} bytes")
    logger.info(f"  Title: {result.get('title', 'N/A')}")
    logger.info(f"  Description: {result.get('description', 'N/A')}")

    logger.info(f"\nHTML Structure:")
    structure = result.get('structure', {})
    logger.info(f"  Tables: {structure.get('tables', 0)}")
    logger.info(f"  Lists: {structure.get('lists', 0)}")
    logger.info(f"  Forms: {structure.get('forms', 0)}")
    logger.info(f"  Divs with classes: {structure.get('divs_with_classes', 0)}")
    logger.info(f"  Common classes: {', '.join(structure.get('common_classes', [])[:10])}")

    # Show snippet of text content
    text = result.get('text', '')
    if text:
        logger.info(f"\nText Content Preview (first 500 chars):")
        logger.info(text[:500])

    return result


async def diagnose_template_selectors():
    """Use Playwright to diagnose which selectors work on screener.in"""
    from playwright.async_api import async_playwright

    logger.info("\n" + "="*80)
    logger.info("DIAGNOSING TEMPLATE SELECTORS")
    logger.info("="*80)

    url = "https://www.screener.in/company/BHARTIARTL/consolidated/"

    # Selectors from template
    selectors_to_test = {
        "Company Name": "h1.h2",
        "Market Cap": "#top-ratios > li:nth-child(1) > span.number",
        "Current Price": "#top-ratios > li:nth-child(2) > span.number",
        "Stock P/E": "#top-ratios > li:nth-child(3) > span.number",
        "Book Value": "#top-ratios > li:nth-child(4) > span.number",
        "Dividend Yield": "#top-ratios > li:nth-child(5) > span.number",
        "ROCE": "#top-ratios > li:nth-child(6) > span.number",
        "ROE": "#top-ratios > li:nth-child(7) > span.number",
        "Face Value": "#top-ratios > li:nth-child(8) > span.number",
    }

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(
            user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        )
        context.set_default_navigation_timeout(60000)
        context.set_default_timeout(60000)

        page = await context.new_page()

        try:
            logger.info(f"Navigating to: {url}")
            await page.goto(url, wait_until='networkidle', timeout=90000)
            logger.info("Page loaded successfully")

            # Wait for the selector that template expects
            logger.info("Waiting for #company-ratios selector...")
            try:
                await page.wait_for_selector("#company-ratios", timeout=60000)
                logger.info("✓ #company-ratios found")
            except Exception as e:
                logger.error(f"✗ #company-ratios not found: {e}")

            # Test each selector
            logger.info("\nTesting selectors:")
            for field_name, selector in selectors_to_test.items():
                try:
                    element = await page.query_selector(selector)
                    if element:
                        text = await element.text_content()
                        logger.info(f"✓ {field_name}: '{text}' (selector: {selector})")
                    else:
                        logger.warning(f"✗ {field_name}: Element not found (selector: {selector})")
                except Exception as e:
                    logger.error(f"✗ {field_name}: Error - {e} (selector: {selector})")

            # Try alternative selectors
            logger.info("\n--- Testing alternative selectors ---")

            # Check if top-ratios exists
            top_ratios = await page.query_selector("#top-ratios")
            if top_ratios:
                logger.info("✓ #top-ratios element exists")
                # Get all li elements
                li_elements = await page.query_selector_all("#top-ratios li")
                logger.info(f"  Found {len(li_elements)} li elements")
                for idx, li in enumerate(li_elements[:8], 1):
                    text = await li.text_content()
                    logger.info(f"    Li {idx}: {text.strip()[:50]}")
            else:
                logger.warning("✗ #top-ratios element not found")

            # Check company-ratios
            company_ratios = await page.query_selector("#company-ratios")
            if company_ratios:
                logger.info("✓ #company-ratios element exists")
            else:
                logger.warning("✗ #company-ratios element not found")

        finally:
            await context.close()
            await browser.close()


async def main():
    """Run all diagnostic tests"""
    try:
        # Test 1: Check what content is being fetched
        await test_webpage_content()

        # Test 2: Diagnose template selectors
        await diagnose_template_selectors()

        # Test 3: Test template extraction
        template_result = await test_template_extraction()

        # Test 4: Test smart extraction
        smart_template = await test_smart_extraction()

        logger.info("\n" + "="*80)
        logger.info("COMPARISON SUMMARY")
        logger.info("="*80)

        if template_result:
            logger.info(f"Template Extractor: {'SUCCESS' if template_result.get('success') else 'FAILED'}")
            if template_result.get('success'):
                logger.info(f"  - Extracted {template_result.get('row_count', 0)} rows")

        if smart_template:
            logger.info(f"Smart Extractor: SUCCESS (template generated)")
            logger.info(f"  - Generated {len(smart_template.fields)} fields")
            logger.info(f"  - Generated by: {smart_template.schema_definition.metadata.get('generated_by')}")
        else:
            logger.info(f"Smart Extractor: FAILED")

    except Exception as e:
        logger.error(f"Diagnostic failed: {e}", exc_info=True)


if __name__ == "__main__":
    asyncio.run(main())
